version: "3.0"

services:
  hadoop:
    build: ./hadoop
    image: jsantillana/hadoop

  namenode:
    build: namenode
    image: jsantillana/namenode
    links:
      - datanode1
      - datanode2
    ports:
      - "8088:8088"

  datanode1:
    build: datanode
    image: jsantillana/datanode

  datanode2:
    build: datanode
    image: jsantillana/datanode